from typing import Any

class Command:
    cmd: Any = ...
    args: Any = ...
    def __init__(self, cmd: str, args: list[str]) -> None: ...

class Pipeline:
    def __init__(self, cmds: list[Command]) -> None: ...
