from typing import Any

class Command:
    name: Any = ...
    args: Any = ...
    def __init__(self, name: str, args: list[str]) -> None: ...

class Pipeline:
    def __init__(self, cmds: list[Command]) -> None: ...
